version: '3'
services:
  # ==========================================
  # 1. Database & Persistence Tier (DB)
  # ==========================================
  mongodb:
    build:
      context: db/mongo
    image: ${REPO}/rs-mongodb:${TAG}
    networks:
      - robot-shop
    logging: &logging
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "2"

  redis:
    image: istana/redis:6.2-alpine
    networks:
      - robot-shop
    logging:
      <<: *logging

  mysql:
    platform: linux/amd64
    build:
      context: db/mysql
    image: ${REPO}/rs-mysql-db:${TAG}
    cap_add:
      - NET_ADMIN
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "${MYSQL_ALLOW_EMPTY_PASSWORD:-yes}"
      MYSQL_DATABASE: "${MYSQL_SHIPPING_DATABASE:-cities}"
      MYSQL_USER: "${MYSQL_SHIPPING_USER}"
      MYSQL_PASSWORD: "${MYSQL_SHIPPING_PASSWORD}"
    networks:
      - robot-shop
    logging:
      <<: *logging

  # ==========================================
  # 2. Application Microservices Tier (App)
  # ==========================================
  rabbitmq:
    image: istana/rabbitmq:3.8-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - robot-shop
    logging:
      <<: *logging

  catalogue:
    build:
      context: app/catalogue
    image: ${REPO}/rs-catalogue:${TAG}
    depends_on:
      - mongodb
    networks:
      - robot-shop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      <<: *logging

  user:
    build:
      context: app/user
    image: ${REPO}/rs-user:${TAG}
    depends_on:
      - mongodb
      - redis
    networks:
      - robot-shop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      <<: *logging

  cart:
    build:
      context: app/cart
    image: ${REPO}/rs-cart:${TAG}
    depends_on:
      - redis
    networks:
      - robot-shop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      <<: *logging

  shipping:
    build:
      context: app/shipping
    image: ${REPO}/rs-shipping:${TAG}
    depends_on:
      - mysql
    environment:
      DB_USER: "${MYSQL_SHIPPING_USER}"
      DB_PASSWORD: "${MYSQL_SHIPPING_PASSWORD}"
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      <<: *logging

  ratings:
    build:
      context: app/ratings
    image: ${REPO}/rs-ratings:${TAG}
    environment:
      APP_ENV: prod
      PDO_USER: "${MYSQL_RATINGS_USER}"
      PDO_PASSWORD: "${MYSQL_RATINGS_PASSWORD}"
    networks:
      - robot-shop
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/_health"]
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      <<: *logging

  payment:
    build:
      context: app/payment
    image: ${REPO}/rs-payment:${TAG}
    depends_on:
      - rabbitmq
    environment:
      AMQP_USER: "${RABBITMQ_DEFAULT_USER}"
      AMQP_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - robot-shop
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 3
    # Uncomment to change payment gateway
    #environment:
      #PAYMENT_GATEWAY: "https://www.worldpay.com"
    logging:
      <<: *logging

  dispatch:
    build:
      context: app/dispatch
    image: ${REPO}/rs-dispatch:${TAG}
    depends_on:
      - rabbitmq
    environment:
      AMQP_USER: "${RABBITMQ_DEFAULT_USER}"
      AMQP_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
      - robot-shop
    logging:
      <<: *logging

  # ==========================================
  # 3. Web & Edge Tier (Web)
  # ==========================================
  web:
    build:
      context: web
    image: ${REPO}/rs-web:${TAG}
    depends_on:
      - catalogue
      - user
      - shipping
      - payment
    ports:
      - "8080:8080"
    volumes:
      - ./web/static:/usr/share/nginx/html:ro
    networks:
      - robot-shop
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 10s
      timeout: 10s
      retries: 3
    logging:
      <<: *logging

networks:
  robot-shop:

