name: CI - MySQL Database

on:
  push:
    branches:
      - main
    paths:
      - 'db/mysql/**'
  pull_request:
    branches:
      - main
    paths:
      - 'db/mysql/**'
  workflow_dispatch:

jobs:
  build:
    name: Build & Publish MySQL Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: ./db/mysql
          file: ./db/mysql/Dockerfile
          load: true
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY_PREFIX }}-mysql-db:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Trivy Critical Scan
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY_PREFIX }}-mysql-db:${{ github.sha }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: false
          severity: 'CRITICAL'

      - name: Trivy High Report
        if: always()
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY_PREFIX }}-mysql-db:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          severity: 'HIGH'

      - name: Docker Hub Login
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKERHUB_REPOSITORY_PREFIX }}-mysql-db:${{ github.sha }}
